theme: jekyll-theme-minimal
description: I'm a Mechatronic Engineer student currently under a double degree graduation on POLI-UPE (Brazil) and Polictenico di Torino (Italy) and CEO of Sqr2ed Tech. I'm a technologies enthusiast passionate about programming and gaming, trying to improve myself and stay tuned to the latest tech news, tools and gadgets.
logo: assets/images/logo.png
title: Rafaziz's Portifolio
show_downloads: true
