theme: jekyll-theme-minimal
description: I am a Mechatronic Engineer student currently under a double degree graduation on POLI-UPE (Brazil) and Polictenico di Torino (Italy) and CEO of Sqr2ed Tech. I'm a technologies enthusiast passionate about programming and gaming, always trying to improve myself and be updated with the latest news, tools and gadgets of the technologies world. Enjoy my portifolio.
logo: assets/images/logo.png
title: Rafaziz's Portifolio
show_downloads: true
